### ISSUE TITLE
Indicator wrong when server and browser timezone are different

### ISSUE THREAD

**Issue by williwacker** [BasvanH/habpanel-widget-lastupdate-indicator#1]
I was just recently in Canada and was checking my OpenHub panels and found the lastupdate indicators out of time by 5-6h.  This happens while the javascript library uses the browser timezone and the server the home zone.  To prevent this it makes sense only working with UTC timestamps in the JS script.
I have changed the code to make it work:
`				
function getLastupdate() {

	try {
		var state = $scope.itemState($scope.config.lastupdate_item);						
		var now = new Date();
//		var tzo = now.getTimezoneOffset()
//		if (tzo != 0){
//			now = new Date(now.getTime() - tzo*60000);
//		}
		var last = new Date(state.slice(0, state.lastIndexOf("+")) + "Z"); //Crappy safari doesnt like timezone format
		var state_tzo = last.getTimezoneOffset()  //get state timezone
		var timeDiff = Math.abs(last.getTime() + state_tzo*60000 - now.getTime());
`

**Comment by BasvanH** [comment]
Ok nice one, if you make a pull request I'll be more then happy to pull it into master. Thanks!

**Comment by BasvanH** [comment]
Thank you for the pull.
